### ISSUE TITLE
compilation on mac

### ISSUE THREAD

**Issue by cfgammie** [AFD-Illinois/symphony#1]
Does not compile out of the box on mac using clang.

**Comment by mchandra** [comment]
Can you check if the current version on branch:master works?

**Comment by cfgammie** [comment]
Nope, doesn't work.

Output of cmake and make attached.  Can't find gsl libraries.

gsl is installed, by the way, and I can compile iharm2d (which uses
gsl) with gcc5 but not with the default cc, which is clang.

Setting CC to gcc5 and rerunning cmake does not help.

C.

Charles F. Gammie
Professor of Astrophysics
(217) 333-8646 | gammie@illinois.edu
http://rainman.astro.illinois.edu/gammie

On 3/1/16 4:50 AM, Mani Chandra wrote:
> Can you check if the current version on branch:master works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_AFD-2DIllinois_symphony_issues_1-23issuecomment-2D190544703&d=BQMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=JioL_fCI9XvL4xQK5iFnYmD_NlnLS7P1udnKGheApuA&m=1JrtAbAPKLCyiOMnm7EpSdIpLSF0kS63QxL4zRO5-VY&s=8WKRieEYGACIiv9YZVGOyptR-xNvGNY6xIANirA--CQ&e=>.
>

-- MKL library not found
-- Checking for [Accelerate]
-- Libraries found
-- CBLAS library found

#################
# Build options #
#################

C Compiler       : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
C_FLAGS          :  -std=c99 -Wall -O3
GSL Libraries    : /opt/local/lib/libgsl.dylib
CBLAS Libraries  : /System/Library/Frameworks/Accelerate.framework
NumPy dir        : /Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/numpy/core/include
Cython           : /Library/Frameworks/Python.framework/Versions/Current/bin/cython

-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   kappa
   maxwell_juettner
   power_law

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/gammie/tmp/symphony-master/src

Scanning dependencies of target kappa
[  4%] Building C object kappa/CMakeFiles/kappa.dir/kappa.c.o
In file included from /Users/gammie/tmp/symphony-master/src/kappa/kappa.c:1:
In file included from /Users/gammie/tmp/symphony-master/src/kappa/kappa.h:4:
/Users/gammie/tmp/symphony-master/src/kappa/../symphony.h:2:10: fatal error: 'gsl/gsl_spline.h' file not found
#include <gsl/gsl_spline.h>
         ^
1 error generated.
make[2]: *** [kappa/CMakeFiles/kappa.dir/kappa.c.o] Error 1
make[1]: *** [kappa/CMakeFiles/kappa.dir/all] Error 2
make: *** [all] Error 2

**Comment by aapandy2** [comment]
symphony should now compile and run on mac (with python from anaconda).
