### ISSUE TITLE
Significant differences in power law Stokes V absorption coefficient fitting formula

### ISSUE THREAD

**Issue by pkgw** [AFD-Illinois/symphony#11]
If I use Symphony's fitting formula to calculate a Stokes V absorption coefficient, I get results that differ significantly from the detailed calculation. For instance:

```
from __future__ import print_function

from symphonyPy import alpha_nu_fit_py, alpha_nu_py, POWER_LAW, STOKES_V

params = (
    3e9, # nu
    250, # B
    3e7, # n_e
    2.5, # theta
    POWER_LAW,
    STOKES_V,
    10.,
    2.2, # power-law p
    0.1,
    1000.,
    1e7,
    3.5,
    10
)


print('detailed:', alpha_nu_py(*params))
print('fit:', alpha_nu_fit_py(*params))
```

Results in:

```
detailed: 2.85236657545e-06
fit: -4.86456153294e-08
```

Getting different signs makes a big difference if you're integrating a radiative transfer equation! I haven't quite figured out for myself which sign is *right*, though.

I also see some differences between the equation written in the paper and what's implemented in `power_law_fits.c`.

**Comment by aapandy2** [comment]
## Sign error in power-law Stokes V absorptivity

Calculating the Stokes V absorptivities using the integrator results in a sign change at observer_angle = 90 degrees, which was erroneously not captured in the power-law and kappa absorptivity formulae.  A similar behavior occurs for the emissivity, and there is a corresponding bug in the kappa Stokes V emissivity formula.  

In all three bugs, the existing formulae have signs that match the integrated absorptivities/emissivities for observer angles less than 90 degrees, and then deviate at angles greater than 90 degrees.  Below is a plot of this issue for the power-law Stokes V absorptivity.
![pl_v_fit_bug](https://cloud.githubusercontent.com/assets/10888531/23631800/2ca4ffe6-0285-11e7-8a54-525dfbba2379.png)

All three of the bugs were patched by multiplying the existing formulae by the term
`sign_bug_patch = cos(params->observer_angle) / fabs(cos(params->observer_angle))`
which corrects the sign.  Applying this fix to the formulae used in the above plot yields:
![pl_v_fit_bug_patched](https://cloud.githubusercontent.com/assets/10888531/23632117/4d12a606-0286-11e7-909f-1aaf8f2095f6.png)
which has the correct behavior.

## Difference between power-law Stokes V absorptivity formula in Pandya+ 2016 and corresponding formula in symphony

The power-law Stokes V formula in symphony is slightly different from the one in Pandya+ 2016.  The latter is slightly simplified at the cost of about 2% relative error in the fitting formula, and a more accurate (but more complicated) version is used in symphony.  The plot below compares the two formulae.
![paper_fit_vs_symphony_fit](https://cloud.githubusercontent.com/assets/10888531/23632229/a16f47e0-0286-11e7-8d56-ec9f58ed4ee9.png)

## Difference in magnitude between integrated result and fit at nu = 3e9

I am having trouble reproducing the values in the above comment.  After running your code, I get:
```
('detailed:', 2.6713744510495884e-06)
('fit:', -2.4274750865223796e-07)
```
though in both cases there is an order of magnitude difference between the integrated result and the fitting formula.  In my case, I think this is just explained by inaccuracy in the formula at low frequencies; see the plot below.
![discrepancy_low_nu](https://cloud.githubusercontent.com/assets/10888531/23632805/eda0b688-0288-11e7-83ca-bc74ef378e91.png)

**Comment by pkgw** [comment]
Thanks for the detailed reply! Clearly the main thing was that I wasn't paying attention and didn't even think about the importance of the θ > π/2 crossing point.

When I rerun the computation I get the same alpha_nu value as you, 2.67137445e-06. I'm not sure what changed.
