### ISSUE TITLE
Inconsistent sign in Faraday coefficient fits

### ISSUE THREAD

**Issue by aapandy2** [AFD-Illinois/symphony#16]
The sign in the Faraday coefficient fits coded up in maxwell_juettner_fits.c is inconsistent with our treatment, as they are from Dexter (2016) which uses a different coordinate system (k along the y axis).

**Comment by avjoshi21** [comment]
If I am not mistaken, all the fits produce the same sign as the original function, which is consistent with the current coordinate system (sign of j_Q being negative). Are there two sign errors that are masking this?

**Comment by aapandy2** [comment]
It turns out that it was consistent -- I must have corrected the signs when I coded the fits up.
