### ISSUE TITLE
Specify copyright holders and a license

### ISSUE THREAD

**Issue by pkgw** [AFD-Illinois/symphony#2]
If you don't specify a license for the symphony code, technically [it is illegal for anyone to use it](http://newton.cx/~peter/2016/07/code-copyright-and-licenses-the-bare-minimum-you-should-know/). People will use it anyway, but it is better to have the legalities all dealt with correctly!

I would suggest assigning the copyright to something nebulous like "the Symphony team" and an MIT License, but license choice does carry real implications so it's worth thinking about which one you want.

**Comment by aapandy2** [comment]
Added a LICENSE file and assigned copyright to the Symphony team.
