### ISSUE TITLE
Specify version number and make a release

### ISSUE THREAD

**Issue by pkgw** [AFD-Illinois/symphony#3]
Hopefully symphony will keep on growing and improving. In order for people to know which version of the code was used in a given paper, I'd argue that it should have a version number assigned! The simplest way to start is just to put a version number in the README file and make a Git tag. Then
Github makes it very easy to label a release and create tarballs of it: [here](https://github.com/AFD-Illinois/symphony/releases). Having a release tarball is important for things like being able to integrate symphony into the Anaconda Python build system.

**Comment by mchandra** [comment]
Do you think we could simply specify a commit hash in a paper?

**Comment by pkgw** [comment]
That's one way to do it. If you go that route, you should find some way to embed the Git commit into the C and Python code upon install, so someone can run something like:

```
import symphonyPy
print (symphonyPy.__version__)
```

to know what version they're running.

But I'd encourage the use of traditional version numbers — they're not much more work, they fit in better with other systems (e.g. packaging systems), and if you're using version 1.0 and you read a paper that says it uses version 2.0, that's more meaningful than `e93faa3` vs. `7270ff0`.

**Comment by mchandra** [comment]
Ok, we'll assign revision numbers. Do you have a sensible scheme for doing this? When should 1.0 -> 2.0, and not 1.1, or 1.0.1?

**Comment by pkgw** [comment]
A popular thing these days is "semantic versioning": [see here](http://semver.org/). The rules are aimed at more "software"-y projects, but you could try to follow the same spirit. For instance, if you completely changed one of the underlying algorithms for computing a certain quantity, that would probably merit a bump in the major version number (1.0 → 2.0).
